<?php
/**
 * Страница "Форма создания новой темы".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Theme creation form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/create.png' ?>" />
    </div>
    <p>The form appears after clicking on the button <b>"Create"</b> on the toolbar of <a href="<?= $url('grid') ?>">the list of themes</a>.</p>
    <p>The process of creating a new theme involves using a theme selected from the list as a base template; all parameters of the source theme are copied and can subsequently be modified.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Directory.</b> You must specify a local path as the directory name for the new theme—it must start with "/", <em>for example, "/new-theme"</em>.;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Theme name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Theme description;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Author.</b> Theme author;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>License.</b> License applicable to the theme, <em>e.g., "GPL-2.0-or-later"</em>;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Version.</b> Theme version, <em>e.g., "1.0"</em>.</li>
    </ul>
</article>