<?php
/**
 * Страница "Список тем оформлений".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список тем оформлений</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>Список шаблонов оформления, используемых для визуализации сайта и интерфейса Панели управления.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Название.</b> Название темы оформления, описание и версия;</li>
        <li><b>Автор.</b> Автор темы оформления;</li>
        <li><b>Версия.</b> Версия темы оформления;</li>
        <li><b>Назначение.</b> Назначение темы оформления: Панель управления, Сайт;</li>
        <li><b>Лицензия.</b> Лицензия применяемая для темы оформления;</li>
        <li><b>По умолчанию.</b> Тема оформления назначена для сайта или для Панели управления.</li>
        <li><b>Статус.</b> Статус темы оформления: установлена, не установлена, ошибка, неизвестно.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-create.svg' ?>" /> <b>Создать.</b> Открывает форму для создания новой темы оформления, используя в качестве основы тему, выбранную из списка;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Загрузить.</b> Открывает форму для загрузки пакета темы оформления в формате zip-архива;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Установить.</b> Устанавливает тему оформления выбранную из списка;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Удалить.</b> Полностью удаляет тему оформления;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет загруженный пакет темы оформления;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Демонтаж.</b> Демонтаж (удаление) установленной темы без удаления её репозитория;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызывает форму для просмотра информации о теме оформления;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение тем оформлений в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список тем оформлений;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранной из списка теме оформления;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает или скрывает столбцы, которые скрыты по умолчанию;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Открывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Открывает форму поиска тем оформлений в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Выполняет фильтрацию списка тем оформлений по их назначению: все темы, темы для сайта или Панели управления.</li>
    </ul>
</article>