<?php
/**
 * Страница "Форма установки темы".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Theme setup form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/install.png' ?>" />
    </div>
    <p>The form appears after clicking on the button <b>"Install"</b> on the toolbar of <a href="<?= $url('grid') ?>">the themes list</a>.</p>
    <p>Theme metadata is contained in the package.json file, located in the theme's root directory. This file defines key theme attributes (name, description, version, etc.) used by the system when installing, building, and applying the theme.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Name.</b> Theme name;</li>
        <li><b>Description.</b> Theme description;</li>
        <li><b>Author.</b> Theme author;</li>
        <li><b>License.</b> License applied to the theme.</li>
        <li><b>Version.</b> Theme version;</li>
        <li><b>Keywords.</b> Key words and phrases that best capture the essence of the design theme. Used in searches.</li>
    </ul>
</article>