<?php
/**
 * Страница "Форма информации о теме".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Информации о теме</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/package.png' ?>" />
    </div>
    <p>Форма с информацией о теме появляется после выбора пункта <b>"Информации о теме"</b> контекстного меню выбранной темы.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b> Название темы оформления;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание темы оформления;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Автор.</b> Автор темы оформления;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Лицензия.</b> Лицензия, применяемая к теме оформления;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Версия.</b> Версия темы оформления;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Ключевые слова.</b> Основные слова и фразы, которые лучше всего отражают суть темы оформления. Применяются в  поиске.</li>
    </ul>
</article>