<?php
/**
 * Страница "Форма информации о теме".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Theme information form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/package.png' ?>" />
    </div>
    <p>The theme information form appears after selecting the <b>"Theme information"</b> item from the context menu of the selected theme.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Theme name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Theme description;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Author.</b> Theme author;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>License.</b> License applied to the theme.</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Version.</b> Theme version;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Keywords.</b> Key words and phrases that best capture the essence of the design theme. Used in searches.</li>
    </ul>
</article>