<?php
/**
 * Страница "Форма загрузки темы".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Theme upload form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/upload.png' ?>" />
    </div>
    <p>The form appears after clicking on the <b>"Load"</b> button on <a href="<?= $url('grid') ?>">the themes list</a> toolbar.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Purpose.</b> The design theme can be applied selectively: either to the Control Panel or to the public part of the site;</li>
        <li><span class="g-help-fld g-help-fld_file"></span> <b>Theme file.</b> A theme file in ZIP (.zip) format is selected and uploaded. The accepted file type is strictly limited to ZIP—other archive formats are not supported. Before processing, the system validates the archive structure and the presence of required theme files..</li>
    </ul>
</article>